### ISSUE TITLE
Migrate website to v2

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website-v2#1]
We can refer to: https://github.com/casbin/casbin-website/pull/265

**Comment by Shivansh-yadav13** [comment]
@hsluoyz can I try working on this?

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 sure

**Comment by hsluoyz** [comment]
Initially done at: https://github.com/casbin/casbin-website/pull/265#issuecomment-1152577649
