### ISSUE TITLE
Setup netlify preview on every PR

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website-v2#11]
Like: https://github.com/casbin/casbin-website/pull/351#issuecomment-1153051707

![image](https://user-images.githubusercontent.com/3787410/173583430-32ebc58a-9368-4429-bd53-4d49ae3096b5.png)

**Comment by hsluoyz** [comment]
@EmperorYP7 @Shivansh-yadav13

**Comment by EmperorYP7** [comment]
Done, Netlify will deploy a preview for forthcoming PRs.

**Comment by hsluoyz** [comment]
@EmperorYP7 great! Can you make a PR (like fix a typo) to test it?
