### ISSUE TITLE
website homepage is not responsive in mobile view

### ISSUE THREAD

**Issue by Amishakumari544** [casbin/casbin-website-v2#127]
![Screenshot_2022-12-18-14-21-58-758_com android chrome](https://user-images.githubusercontent.com/49230384/208289415-2e4205d7-9d2d-42e3-9e23-0bd5ef857f0f.jpg)

**Comment by Amishakumari544** [comment]
Hi @hsluoyz I want to work on this issue

**Comment by hsluoyz** [comment]
PR is welcome!

**Comment by Amishakumari544** [comment]
oki

**Comment by Amishakumari544** [comment]
Hi, @hsluoyz I am trying to commit the code but it's giving me some errors with which I am not familiar and there is no documentation also on how to commit and create PR by the following convention.
Let me know if there is or I will create that issue also

**Comment by Hustler930** [comment]
I want to work on this issue please assign me this issue

**Comment by inviBeast** [comment]
I would be highly obliged if you assign me this issue.

**Comment by codesmith25103** [comment]
Can you please assign me this issue?

**Comment by hsluoyz** [comment]
Any one can work on this issue. If you want to do it, just do it. If the PR quality is met, it will be merged. Please do not reply under this issue again and again.
