### ISSUE TITLE
Navbar is not responsive.

### ISSUE THREAD

**Issue by Ankitchaudharyy** [casbin/casbin-website-v2#131]
Navbar Items overlap each other when the width of the screen is reduced.

- Screenshot attached
<img width="1052" alt="Screenshot 2022-12-26 at 11 24 10 PM" src="https://user-images.githubusercontent.com/46367738/209573506-13ca7579-eeac-48c9-be55-dff1d7062e32.png">

**Comment by Ankitchaudharyy** [comment]
I can work on this issue. Please assign it to me.

**Comment by Rew0611** [comment]
I want to work on this issue

**Comment by anurag0006** [comment]
Hii @hsluoyz, As the issue is still open i wanna work on this issue...Can You please assign this to me?

**Comment by MahendraBishnoi29** [comment]
@hsluoyz is it still open? if yes then i want to work on it

**Comment by mohd-asad** [comment]
Hi, I can fix this bug, plz assign it me.

**Comment by mohd-asad** [comment]
On the navbar, titles are shifted downward. I can set them in the middle.
