### ISSUE TITLE
[Bug] Navbar is too messy , github icon is hindered by two other icons

### ISSUE THREAD

**Issue by Rew0611** [casbin/casbin-website-v2#132]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/96280175/209636400-0ecfce4d-ab40-4314-b73f-5c1caa707b4a.png">

Navbar is too messy , github icon is hindered by two other icons

**Comment by hsluoyz** [comment]
Dup with: https://github.com/casbin/casbin-website-v2/issues/131
