### ISSUE TITLE
Why is the page content not up-to-date

### ISSUE THREAD

**Issue by hailaz** [casbin/casbin-website-v2#140]
https://casbin.org/docs/adapters
![image](https://user-images.githubusercontent.com/29968474/213160192-2516da08-159c-4fed-9b57-9ef7820c4d03.png)

https://github.com/casbin/casbin.io/blob/master/docs/adapters.html

![image](https://user-images.githubusercontent.com/29968474/213160512-ce90ff47-6ba7-478b-887d-9e4daba1d5cb.png)

**Comment by hsluoyz** [comment]
@hailaz ok now:

![image](https://user-images.githubusercontent.com/3787410/213161600-9adedaad-c2b1-483e-949f-90b5587115da.png)
