### ISSUE TITLE
Update installation command

### ISSUE THREAD

**Issue by harshalmittal4** [casbin/casbin-website-v2#145]
While installing Casbin for Go as per instructions [here](https://casbin.org/docs/get-started#installation) using the `go get` command I received the following error - 
```
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```
after which found that go get is deprecated (https://go.dev/doc/go-get-install-deprecation). 

I installed using `go install github.com/casbin/casbin/v2@latest`. 
It looks like the installation command need to be updated in the docs. Please let me know, would be happy to send a PR. Thanks!

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
@harshalmittal4 Thanks for your feedback, but I tried to follow your instructions and did not install successfully
![image](https://user-images.githubusercontent.com/46661603/216829671-c91e84e5-deef-40e1-b55e-d8e1d0b6144b.png)

After reading [Deprecation of 'go get' for installing executables](https://go.dev/doc/go-get-install-deprecation), it is my understanding that `go get` is just no longer used to **"install executables"**, not completely deprecated.

As indicated in the picture, casbin is not a main package, so it cannot be installed via `go install`. You should get casbin via `go get`, just like the official website.

In addition, according to your error message, you may not execute `go get` in the correct directory (where the `go.mod` file exists), so an error occurred
```bash
go: go.mod file not found in current directory or any parent directory.
```

I tried to install casbin using `go get` and it worked

![image](https://user-images.githubusercontent.com/46661603/216830486-27aae729-68b9-4a6d-8c62-505d26f96ec8.png)

Hope this helps you

**Comment by harshalmittal4** [comment]
Oh sorry @PokIsemaine , I ran `go install` after which it started downloading some projects due to which I switched to another window.  I just checked that it's not installed.
![Screenshot 2023-02-05 at 10 14 56 PM](https://user-images.githubusercontent.com/24206326/216832448-87ce0353-684d-4e6a-8d8a-73df248454f2.png)


I was not in the correct directory, I am able to install it now via `go get`. Thanks and sorry to bother you with this! Closing the issue

**Comment by harshalmittal4** [comment]
Hey @PokIsemaine , 
unrelated to this issue, I find the Casbin project piquing my interest as it's related to policy enforcement and control, which is similar to something to what I've worked on earlier, and also because I'm looking for a Go project to contribute to for learning and developing my skills. 
I wish to participate work on a Casbin project for GSoC and currently exploring as much as I can about the project. Would you be please able to help me know if there are some easy issues that I can try?

**Comment by PokIsemaine** [comment]
@harshalmittal4 you can try to contact @hsluoyz in
https://gitter.im/casbin/gsoc

**Comment by harshalmittal4** [comment]
Thanks
