### ISSUE TITLE
Sidebar disappears once collapsed

### ISSUE THREAD

**Issue by Abhinavxox** [casbin/casbin-website-v2#153]
### description:
There is an issue with the sidebar as it lacks an option to be expanded once it has been collapsed using the collapse button. To bring it back, the only options available are either to reload the page or navigate to a different section and return to the original section.

[casbin.webm](https://user-images.githubusercontent.com/72064600/230952946-0646c2d8-44c8-4f70-8f2a-66c22d405d04.webm)

### authors: Abhinavxox

**Comment by hsluoyz** [comment]
@Abhinavxox hi, can you make a PR to fix it?

**Comment by Abhinavxox** [comment]
> @Abhinavxox hi, can you make a PR to fix it?

Yes, I will do it soon.
