### ISSUE TITLE
Navbar responsive issue

### ISSUE THREAD

**Issue by 777Prabhjot** [casbin/casbin-website-v2#156]
Navbar is not responsive for 1355 to 994 width screens.

**Screen Shot**
<img width="929" alt="Screenshot 2023-04-12 113227" src="https://user-images.githubusercontent.com/68184118/231365496-88c01ef3-589c-4023-8d63-2ea1bb00722e.png">

### **I would love to fix it**

**Comment by hsluoyz** [comment]
@Selflocking

**Comment by arjavsethi** [comment]
hey this issue still arises can i work on this bug?
![image](https://github.com/casbin/casbin-website-v2/assets/75158301/f891a02d-b4bf-432c-8370-e5971fed356a)

**Comment by arjavsethi** [comment]
> hey this issue still arises can i work on this bug? ![image](https://user-images.githubusercontent.com/75158301/252745818-f891a02d-b4bf-432c-8370-e5971fed356a.png)

@hsluoyz

**Comment by Selflocking** [comment]
@arjavsethi You are welcome to work on it.

**Comment by arjavsethi** [comment]
@Selflocking  I was about to create pr but turns out this issue is already solved in this [pr ](https://github.com/casbin/casbin-website-v2/pull/166) and it is waiting to merge
