### ISSUE TITLE
Replace all Gitter community links with Discord

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website-v2#179]
![image](https://github.com/casbin/casbin-website-v2/assets/3787410/fb6f09e5-3f57-43da-af1d-a724b716638a)

In all repos and websites, the links for Gitter should be replaced by the following Discord links, like: https://github.com/casbin/casbin

- casbin: https://discord.gg/S5UjpzGZjN
- casdoor: https://discord.gg/5rPsrAzK7S
- casnode: https://discord.gg/d8dsAWgn43
- gsoc: https://discord.gg/PD9g8wE6X9
- gsod: https://discord.gg/z5TZyJC5uv

Because therer are so many repos, we may need a program to do it automatically.

**Comment by Selflocking** [comment]
For comparison, here are the badges in repo

[![Go Report Card](https://goreportcard.com/badge/github.com/casbin/casbin)](https://goreportcard.com/report/github.com/casbin/casbin) [![Build Status](https://travis-ci.com/casbin/casbin.svg?branch=master)](https://travis-ci.com/casbin/casbin) [![Coverage Status](https://coveralls.io/repos/github/casbin/casbin/badge.svg?branch=master)](https://coveralls.io/github/casbin/casbin?branch=master) [![Godoc](https://godoc.org/github.com/casbin/casbin?status.svg)](https://pkg.go.dev/github.com/casbin/casbin/v2) [![Release](https://img.shields.io/github/release/casbin/casbin.svg)](https://github.com/casbin/casbin/releases/latest) [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/casbin/lobby) [![Sourcegraph](https://sourcegraph.com/github.com/casbin/casbin/-/badge.svg)](https://sourcegraph.com/github.com/casbin/casbin?badge)

Available styles are as follows:

[![Discord](https://discord.com/api/guilds/1125382348737884200/widget.png)](https://discord.gg/ayhmjFeZ9) [![Discord](https://img.shields.io/badge/discord-join%20chat-5865F2?logo=discord)](https://discord.gg/ayhmjFeZ9) [![Discord](https://img.shields.io/discord/1125382348737884200?label=discord&color=5865f2)](https://discord.gg/ayhmjFeZ9) [![Discord](https://img.shields.io/discord/1125382348737884200?logo=discord&label=discord&color=5865F2
)](https://discord.gg/ayhmjFeZ9) [![Discord](https://img.shields.io/discord/1125382348737884200?style=flat-square&logo=discord&label=discord&color=5865F2
)](https://discord.gg/ayhmjFeZ9)

I prefer [![Discord](https://img.shields.io/discord/1125382348737884200?logo=discord&label=discord&color=5865F2
)](https://discord.gg/ayhmjFeZ9)

To display the number of online users, the following settings are required

![image](https://github.com/casbin/casbin-website-v2/assets/53544726/bbc93f0a-e1d9-4d63-87a0-9109e7883f6f)
![image](https://github.com/casbin/casbin-website-v2/assets/53544726/bb9f1664-04e0-4068-8a12-fa3191831718)
![image](https://github.com/casbin/casbin-website-v2/assets/53544726/803c35dd-7b96-4d68-9df5-79745c70ebd4)

## Details

### [Official](https://discord.com/developers/docs/resources/guild#get-guild-widget-image)

[![](https://discord.com/api/guilds/1125382348737884200/widget.png)](https://discord.gg/ayhmjFeZ9)

```md
[![Discord](https://discord.com/api/guilds/1125382348737884200/widget.png)](https://discord.gg/ayhmjFeZ9)
```

### [Shields](https://shields.io/) 

refer to https://shields.io/badges/discord


[![Discord](https://img.shields.io/badge/discord-join%20chat-5865F2?logo=discord)](https://discord.gg/ayhmjFeZ9) [![Discord](https://img.shields.io/discord/1125382348737884200?label=discord&color=5865f2)](https://discord.gg/ayhmjFeZ9) [![Discord](https://img.shields.io/discord/1125382348737884200?logo=discord&label=discord&color=5865F2
)](https://discord.gg/ayhmjFeZ9) [![Discord](https://img.shields.io/discord/1125382348737884200?style=flat-square&logo=discord&label=discord&color=5865F2
)](https://discord.gg/ayhmjFeZ9)

```md
[![Discord](https://img.shields.io/badge/discord-join%20chat-5865F2?logo=discord)](https://discord.gg/ayhmjFeZ9)

[![Discord](https://img.shields.io/discord/1125382348737884200?label=discord&color=5865f2)](https://discord.gg/ayhmjFeZ9)

[![Discord](https://img.shields.io/discord/1125382348737884200?logo=discord&label=discord&color=5865F2
)](https://discord.gg/ayhmjFeZ9)

[![Discord](https://img.shields.io/discord/1125382348737884200?style=flat-square&logo=discord&label=discord&color=5865F2
)](https://discord.gg/ayhmjFeZ9)
```
