### ISSUE TITLE
Row alignment and cloud native (.......) now show for small device 

### ISSUE THREAD

**Issue by techmannih** [casbin/casbin-website-v2#214]
hello 
I found an issue an issue in your website in which Row alignment and cloud native (.......) now show for small device like moblie phones or below 530px.
I want to work on this issue please assign  me
**Row alignment** 
![Screenshot_2023-10-21_19-05-59](https://github.com/casbin/casbin-website-v2/assets/125847751/9a2277ea-bb33-4548-8acf-6661097c2215)

**cloud native (.......) now show**
![Screenshot_2023-10-21_19-00-35](https://github.com/casbin/casbin-website-v2/assets/125847751/c3bb009b-bee7-4058-adad-8d4518449ea3)
![Screenshot_2023-10-21_19-02-27](https://github.com/casbin/casbin-website-v2/assets/125847751/929c8704-accf-46da-9091-046b9c534131)

**Comment by techmannih** [comment]
Hello @hsluoyz 
I want to work on this issue ....assigned me please

**Comment by hsluoyz** [comment]
@techmannih ok

**Comment by techmannih** [comment]
@hsluoyz  can you assign me this issue . i will create PR
