### ISSUE TITLE
Add Code highlight for Casbin CSV policy

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website-v2#49]
e.g., https://casbin.org/docs/abac

![image](https://user-images.githubusercontent.com/3787410/178026242-f0ad7c0d-31df-4a90-919d-9f959fed4962.png)

The code coloring should be like: https://casbin.org/editor (source code is: https://github.com/casbin/casbin-editor)

![image](https://user-images.githubusercontent.com/3787410/213917068-3d3260a1-6bb3-4a3b-bebb-93bbc13d20b2.png)

**Comment by hsluoyz** [comment]
@Selflocking

**Comment by ZhengLin-Li** [comment]
> The CSV formatter doesn't work. We need to create our own.

what do we need our CSV file look like?

**Comment by hsluoyz** [comment]
@ZhengLin-Li see updated original post

**Comment by oviecodes** [comment]
hello @hsluoyz  I'm a new contributor and would like to know if I can pick this up.

**Comment by hsluoyz** [comment]
Done now:

![image](https://user-images.githubusercontent.com/3787410/230069337-3d939243-e7f8-40cd-bc49-00e7b102f8aa.png)
