### ISSUE TITLE
Policy Persistence and Policy Enforcement at Scale images do not stay centered between certain breakpoints!!

### ISSUE THREAD

**Issue by SteveSayantan** [casbin/casbin-website-v2#51]
![image](https://user-images.githubusercontent.com/92118155/178030020-7bbd343d-23ad-4d07-b25c-624b8167dd4b.png)

# Issue
As seen in the image, the figures tend to shift to the left between screen size 550px and 998px (approx.). 
## Type of Issue:
Front End
## Typical Behavior:
The images should stay centered at any screen size.
### Platform:
Windows 10, Browser: Chrome

**Comment by hsluoyz** [comment]
@SteveSayantan good! Can you fix this?

**Comment by SteveSayantan** [comment]
I would definitely like to give it a try!! But as I've just started learning React, it may take some time.

**Comment by SteveSayantan** [comment]
@hsluoyz I have figured out a fault in the CSS, but unfortunately can't figure out where the CSS is coming from. I have gone through the docs but nothing seems to help. I need some guidance regarding this.

**Comment by Selflocking** [comment]
fix by https://github.com/casbin/casbin-website-v2/pull/56
