### ISSUE TITLE
The algolia search box is empty

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website-v2#66]
https://casbin.io/

![image](https://user-images.githubusercontent.com/3787410/181016166-b7809891-2018-4748-9f52-a22ad3bfb352.png)

**Comment by hsluoyz** [comment]
@Selflocking

**Comment by JalinWang** [comment]
403 again. It worked 2 days ago.
![image](https://user-images.githubusercontent.com/20621784/183642690-7c94d8cb-f367-4b54-a9c8-5189c540a988.png)

**Comment by Selflocking** [comment]
> 

Reapplying for DocSearch, so the previous one is temporarily unavailable
