### ISSUE TITLE
Export the whole docs to PDF

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website-v2#68]
We can find a way to export a Docusaurus v2 site into PDF, so it can be used as the manual for the project.

**Comment by hsluoyz** [comment]
@Selflocking

**Comment by EmperorYP7** [comment]
Docusaurus doesn't support this out of the box. There are various options to do this:

- [md2pdf npm package](https://www.npmjs.com/package/md2pdf)
- [kohheepeace/docusaurus-pdf](https://github.com/kohheepeace/docusaurus-pdf)
- [nuxnik/docusaurus-wkhtmltopdf](https://github.com/nuxnik/docusaurus-wkhtmltopdf)

**Comment by JalinWang** [comment]
> Docusaurus doesn't support this out of the box. There are various options to do this:
> 
> * [md2pdf npm package](https://www.npmjs.com/package/md2pdf)
> * [kohheepeace/docusaurus-pdf](https://github.com/kohheepeace/docusaurus-pdf)
> * [nuxnik/docusaurus-wkhtmltopdf](https://github.com/nuxnik/docusaurus-wkhtmltopdf)

They seem to not support Docusaurus v2. How about https://github.com/kohheepeace/mr-pdf/issues/50?

**Comment by Selflocking** [comment]
> > Docusaurus doesn't support this out of the box. There are various options to do this:
> > 
> > * [md2pdf npm package](https://www.npmjs.com/package/md2pdf)
> > * [kohheepeace/docusaurus-pdf](https://github.com/kohheepeace/docusaurus-pdf)
> > * [nuxnik/docusaurus-wkhtmltopdf](https://github.com/nuxnik/docusaurus-wkhtmltopdf)
> 
> They seem to not support Docusaurus v2. How about [kohheepeace/mr-pdf#50 (comment)](https://github.com/kohheepeace/mr-pdf/issues/50#issuecomment-1115435683) or https://github.com/kohheepeace/mr-pdf#docusaurus-v2-beta?
> 
> updated: It works not well for Docusaurus 2.0.0-rc1 :( https://github.com/casbin/casbin-website-v2/blob/master/package.json#L20 Only part of the documents is captured. ![image](https://user-images.githubusercontent.com/20621784/183284157-3cd14fe8-f825-4fad-be0c-8cc05a2f73e2.png)
> 
> Test command:
> 
> ```shell
> npx mr-pdf --initialDocURLs="https://casbin.io/docs/overview" --contentSelector="article" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".margin-vert--xl a" --coverImage="https://docusaurus.io/img/docusaurus.png" --coverTitle="Docusaurus v2"
> ```

I have tried [docusaurus-prince-pdf](https://github.com/signcl/docusaurus-prince-pdf)
result: https://github.com/Selflocking/casbin-website-v2/releases/tag/pdf
It better than mr-pdf.
But I'm having trouble with [Tabs](https://docusaurus.io/docs/markdown-features/tabs), 
![image](https://user-images.githubusercontent.com/53544726/183291464-a124d281-6e35-46d4-a7c3-bc7bbfca107e.png)

It seems impossible to switch between tabs in pdf

**Comment by hsluoyz** [comment]
@Selflocking we can ignore the tabs for now, that's OK. I tried your generated PDF, the zh docs has issues like:

![image](https://user-images.githubusercontent.com/3787410/183294699-be20b217-8602-47ba-8f67-e347d75da27e.png)

Can you fix it?

**Comment by Selflocking** [comment]
> @Selflocking we can ignore the tabs for now, that's OK. I tried your generated PDF, the zh docs has issues like:
> 
> ![image](https://user-images.githubusercontent.com/3787410/183294699-be20b217-8602-47ba-8f67-e347d75da27e.png)
> 
> Can you fix it?

I am trying to fix it
