### ISSUE TITLE
bug: the CI has failed

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website-v2#7]
See: https://github.com/casbin/casbin-website-v2/runs/6842708416?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/173186690-8154c08b-b8c2-4c62-b2ba-ec2acb6ae830.png)

**Comment by hsluoyz** [comment]
@EmperorYP7

**Comment by EmperorYP7** [comment]
On it

**Comment by hsluoyz** [comment]
Already fixed by: https://github.com/casbin/casbin-website-v2/commits/master
