### ISSUE TITLE
Translate the docs to 100%

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website-v2#74]
Translate the language from 72% to 100%: https://crowdin.com/project/casbin-website

![image](https://user-images.githubusercontent.com/3787410/183867977-4e95ec73-40d8-46b3-b72f-83c24f964a28.png)

**Comment by FoeverA0** [comment]
[WeOpen Star]I would like to help

**Comment by FoeverA0** [comment]
I have finished this task,  please check:)

**Comment by Devansh-365** [comment]
Hey if this issue is still open then I would like to contribute

**Comment by hsluoyz** [comment]
@Devansh-365 what language do you translate?
