### ISSUE TITLE
[Feature] New DynamoDB adapter for Rust

### ISSUE THREAD

**Issue by fospitia** [casbin/casbin-website-v2#95]
Hi.

I made a DynamoDB adapter for Rust, https://github.com/fospitia/dynamodb-adapter, this support Auto-Save.

You can add it to the adapter list, please.

Thank you

**Comment by hsluoyz** [comment]
@fospitia hey, thanks for the contribution! Can you make a PR to: https://github.com/casbin/casbin-website-v2 to add it?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-website-v2/pull/97
