### ISSUE TITLE
Add new tutorials into the tutorial page

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website-v2#98]
See: https://casbin.io/docs/tutorials

**Comment by hsluoyz** [comment]
@yoyo314

**Comment by SaiRev0** [comment]
@hsluoyz I would like to work on this issue if it is not solved yet

**Comment by xsankalp13** [comment]
Hey there
It would be an honour to work on this issue
If it is still available, I'd be glad to work on it

**Comment by IayushCoderJOD** [comment]
I can add more tutorial plz assign this issue to me if it still open @hsluoyz
